language: node_js
sudo: required
dist: trusty
before_script:
  - npm install web-component-tester
  - npm install web-component-tester-proxy
  - npm install bower
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
  - bower install
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run npm test:no-sauce
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then npm run test:sauce-only; fi"
